---
title: "MainFile"
author: "Bakir, Philip, David, Julia"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r setup, echo=FALSE}
#########Style-Guide##########
#'Verwende für den Einzug in der Regel zwei Leerzeichen pro Ebene.
#'
#'Setze Leerzeichen um Zuweisungen, Operatoren und nach Kommas, aber nicht vor.
#'
#'Verwende sinnvolle und beschreibende Namen für Variablen, Funktionen und Objekte.
#'
#'Vermeide Einzelbuchstaben oder Abkürzungen in Variablennamen, es sei denn, sie sind allgemein verständlich.
#'
#' CamelCase für Variablen 
#' 
#' Verwende für den Einzug in der Regel tabular pro Ebene.
#' 
#' Verwende den R-Standard # für Einzeilige Kommentare und #' für Dokumentationskommentare.
#' 
#' Begrenze die Zeilenlänge auf etwa 80 bis 100 Zeichen, um den Code lesbar zu halten. Verwende Zeilenumbrüche, um lange Zeilen aufzuteilen.
#' 
#' Verwende library() zum Laden von Paketen am Anfang deines Skripts oder deiner Funktion.
#' 
#' Vermeide das harte Codieren von Zahlen oder Dateipfaden. Verwende stattdessen Variablen oder Konstanten.
```

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
Daten <- read_csv("Daten.csv")
Daten <- Daten %>% select(-Geburtsdatum)
df_long <- Daten %>% #changing data from wide to long format
  pivot_longer(cols = starts_with("KT"),
               names_to = "Time",
               values_to = "Temperature")


#removing NAs
df_long <-
  df_long %>% mutate(Temperature = ifelse(Temperature < 0, NA, Temperature))  %>% mutate(Time = as.numeric(gsub("KT", "", Time))) 
avgtemp <- df_long %>% group_by(Time,Tag,Iloprost) %>% summarise(avgtemp = mean(Temperature, na.rm = TRUE))



 
df_long %>% ggplot(aes(x = Time, y = Temperature)) +
  geom_point() +
  facet_wrap( ~ Tag) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "Zeit", y = "Körpertemperatur") +
  theme_bw() 
```
```{r}
#bodytemps on each day and hour with mean
avgtemp <- df_long %>% group_by(Time,Tag) %>% summarise(avgtemp = mean(Temperature, na.rm = TRUE))


df_long %>% 
  ggplot(aes(x = Time, y = Temperature)) +
  geom_point(data = avgtemp, aes(y = avgtemp), size = 7, alpha = 1, shape = "-") +
  geom_point(alpha = 0.1) +
  facet_wrap(~ Tag) +
  labs(x = "Uhrzeit", y = "Körpertemperatur") +
  theme_bw()

```

```{r}
#comparison with administered Iloprost
avgtemp <- df_long %>% group_by(Time,Tag,Sklerodermie) %>% summarise(avgtemp = mean(Temperature, na.rm = TRUE))
avgtemp

df_long %>% ungroup %>%
  ggplot(aes(x = Time, y = Temperature)) +
  geom_point(data = avgtemp, aes(y = avgtemp), size = 7, alpha = 1, shape = "-") +
  geom_point(alpha = 0.13) +
  facet_grid(cols = vars(Tag), rows = vars(Sklerodermie))+
  labs(x = "Uhrzeit", y = "Körpertemperatur") +
  theme_bw()
```


```{r}
df_long %>% group_by(Patientennummer) %>% 
  ggplot() #Test
```

```{r}
#'Körpertemperatur verlauf bei Patienten die in den letzen 4 Wochen n viele Attacken hatten, 
#'Fokus auf patienten mit raynaud syndrom und sklerodermie
df1 <- df_long %>% filter(Raynaud == 0, Sklerodermie == 0) %>% 
  group_by(Time,Tag, `Anzahl Raynaud Attacken`) %>% 
  summarise(avgtemp = mean(Temperature, na.rm = TRUE)) %>% drop_na() 

NoAttacks <- df1 %>% filter(`Anzahl Raynaud Attacken` == "0")
Attacks <- df1 %>% filter(`Anzahl Raynaud Attacken` != "0")
Attacks
NoAttacks  %>%
  ggplot(aes(x = Time, y = Temperature)) + 
  geom_point(data = NoAttacks, aes(y =NoAttacks$avgtemp ), size = 7, alpha = 1, shape = "-") +
  facet_grid(cols = vars(Tag), rows = vars(`Anzahl Raynaud Attacken`))+
  labs(x = "Uhrzeit", y = "Körpertemperatur") +
  theme_bw()

Attacks %>%
    ggplot(aes(x = Time, y = Temperature)) + 
  geom_point(data = Attacks, aes(y =Attacks$avgtemp ), size = 7, alpha = 1, shape = "-") +
  facet_grid(cols = vars(Tag), rows = vars(`Anzahl Raynaud Attacken`))+
  labs(x = "Uhrzeit", y = "Körpertemperatur") +
  theme_bw()
```

```{r}
#Körpertemperaturverlauf  Hand, Gesicht, Füße

```



