---
title: "Phils_Code"
author: ""
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r setup, echo=FALSE}
#########Style-Guide##########
#'Verwende für den Einzug in der Regel zwei Leerzeichen pro Ebene.
#'
#'Setze Leerzeichen um Zuweisungen, Operatoren und nach Kommas, aber nicht vor.
#'
#'Verwende sinnvolle und beschreibende Namen für Variablen, Funktionen und Objekte.
#'
#'Vermeide Einzelbuchstaben oder Abkürzungen in Variablennamen, es sei denn, sie sind allgemein verständlich.
#'
#' CamelCase für Variablen 
#' 
#' Verwende für den Einzug in der Regel tabular pro Ebene.
#' 
#' Verwende den R-Standard # für Einzeilige Kommentare und #' für Dokumentationskommentare.
#' 
#' Begrenze die Zeilenlänge auf etwa 80 bis 100 Zeichen, um den Code lesbar zu halten. Verwende Zeilenumbrüche, um lange Zeilen aufzuteilen.
#' 
#' Verwende library() zum Laden von Paketen am Anfang deines Skripts oder deiner Funktion.
#' 
#' Vermeide das harte Codieren von Zahlen oder Dateipfaden. Verwende stattdessen Variablen oder Konstanten.
```

```{r}
Daten <- read_csv("Daten.csv")
# this code chunk formats all hourly data into long format


Daten_longer <- Daten %>% rename("AT 20" = "A 20","AT 22" = "A 22") %>% rename("Notizen" = ...163)%>% 
  mutate(across(matches(".*[0-9]+.*"), as.numeric)) %>% # all columns to numeric
  mutate(across(matches(".*[0-9]+.*"), function(x) {ifelse(x < -50, NA, x)})) %>% # all negative values to NA
  pivot_longer(
    cols = matches(".*[0-9]+.*"), # columns to pivot
    names_to = c("bodypart", "hour"), # new column names, ATTENTION: bodypart contains things like clothing etc.
    names_pattern = "(.*\\D)(\\d{1,2})$", # pattern to separate the original column names
    values_to = "temperatur" # new column name for the values
  ) %>% mutate(hour = as.numeric(hour)) %>%
  mutate(bodypart = gsub(" ","",bodypart)) # remove spaces in bodypart
  
all_bodyparts <- c("TDl", "TDr", "KT", "Tpl", "Tpr", "TF", "TG", "TN", "TZ")
Daten_longer_only_bodypart <- Daten_longer %>% filter(bodypart == all_bodyparts) # only bodypart

Daten_longer_only_bodypart$`Anzahl Raynaud Attacken` <- factor(Daten_longer_only_bodypart$`Anzahl Raynaud Attacken`,levels = c("0","<5","<10",">10",">15",">20"))
Daten_longer_only_bodypart <- Daten_longer_only_bodypart %>% drop_na(contains("Anzahl Raynaud"))

all_bodyparts_by_attacks <- Daten_longer_only_bodypart %>% filter(bodypart != "KT",Raynaud == 0)


all_bodyparts_by_attacks <-
  mutate(
    all_bodyparts_by_attacks,
    bodypart = ifelse(
      bodypart == "TN" | bodypart == "TG",
      "DG",
      bodypart
    ))
all_bodyparts_by_attacks <-
  mutate(
    all_bodyparts_by_attacks,
    bodypart = ifelse(
      bodypart == "Tpl" | bodypart == "Tpr",
      "DH",
      bodypart
    ))
all_bodyparts_by_attacks <-
  mutate(
    all_bodyparts_by_attacks,
    bodypart = ifelse(
      bodypart == "TZ" | bodypart == "TF" | bodypart == "TDl" | bodypart == "TDr",
      "DF",
      bodypart
    ))
all_bodyparts_by_attacks <- all_bodyparts_by_attacks %>%
  mutate(
    all_bodyparts_by_attacks,
    `Anzahl Raynaud Attacken` = ifelse(
      `Anzahl Raynaud Attacken` == "0",
      "0 Raynaud Attacken",
      "mehr als 0 Raynaud Attacken"
    ))

all_bodyparts_by_attacks$`Anzahl Raynaud Attacken` <-
  factor(all_bodyparts_by_attacks$`Anzahl Raynaud Attacken`,
         levels = c("0 Raynaud Attacken", "mehr als 0 Raynaud Attacken"))


Daten_longer_only_bodypart <- Daten_longer_only_bodypart %>%
  mutate(
    `Anzahl Raynaud Attacken` = ifelse(
      `Anzahl Raynaud Attacken` == ">15" | `Anzahl Raynaud Attacken` == ">20",
      ">15",
     `Anzahl Raynaud Attacken`
    ))



Daten_longer_only_bodypart$`Anzahl Raynaud Attacken` <- factor(Daten_longer_only_bodypart$`Anzahl Raynaud Attacken`,levels = c(1,2,3,4,">15"), labels = c("0","1-4","5-9","10-15","15+"))


Daten_longer_only_bodypart$bodypart <- factor(Daten_longer_only_bodypart$bodypart,levels = c("KT","TF","TZ","TG","TN","Tpl","TDl","TDr","Tpr"))
```


```{r}
all_bodyparts_by_attacks_pl <- all_bodyparts_by_attacks %>%
  ggplot(aes(x = hour, y = temperatur)) +
  geom_point(alpha = 0.1, size = 5) +
  facet_grid(
    rows = vars(bodypart),
    cols = vars(`Anzahl Raynaud Attacken`),
    scales = "free"
  ) +
  theme_bw() +
  labs(x = "Uhrzeit", y = "Körpertemperatur") +
  #stat_summary(fun = mean, geom = "point", shape = 1, size = 3, color = "red") +
  geom_smooth(
    method = "loess",
    se = FALSE,
    color = "blue",
    size = 1
  )



all_bodyparts_plot <-
  Daten_longer_only_bodypart  %>% filter(Raynaud == 0, bodypart != "Tpr", bodypart != "TDr") %>% 
  ggplot(aes(x = hour, y = temperatur)) +
  geom_line(aes(group = Patientennummer), alpha = 0.2) +
  geom_point(alpha = 0.2) +
  facet_grid(
    rows = vars(bodypart),
    cols = vars(`Anzahl Raynaud Attacken`),
    scales = "free"
  ) +
  theme_bw() +
  labs(x = "Uhrzeit", y = "Körpertemperatur") +
  #stat_summary(fun = mean, geom = "point", shape = 1, size = 3, color = "red") +
  geom_smooth(method = "loess", se = FALSE) +
  ggtitle("Anzahl Raynaud Attacken in den letzten 4 Wochen:")


label.obs <- c("Tag 1", "Tag 2", "Tag 3", "Tag 4", "Tag 5", "Tag 6")
names(label.obs) <- c(1:6)
Daten_Verteilung <- Daten_longer_only_bodypart %>%
  ggplot(aes(x = hour)) +
  geom_bar() +
  facet_wrap(~Tag, labeller = labeller(Tag = label.obs),ncol = 6) +
  theme_bw() +
  ggtitle("Verteilung der Daten") +
  xlab("Uhrzeit") +
  ylab("Anzahl der Temperatur Messungen")

ggsave(
  "all_bodyparts_plot.pdf",
  all_bodyparts_plot,
  width = 20,
  height = 20,
  units = "cm"
)
ggsave(
  "all_bodyparts_by_attacks_pl.pdf",
  all_bodyparts_by_attacks_pl,
  width = 20,
  height = 20,
  units = "cm"
)
ggsave(
  "Daten_Verteilung.pdf",
  Daten_Verteilung,
  width = 25,
  height = 10,
  units = "cm"
)
```




