---
title: "Teilaufgabe 2b Stat Proj"
author: "David Nikue"
output: html_document
date: "2023-11-14" 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(stringr)


```


```{r}
Daten <- read_csv("Daten.csv")

Farben_Risiko <- c("0"= "darkorange", "1" = "cadetblue")
```


```{r}
#sek Organmanifestation

Daten %>% group_by(`Anzahl Raynaud Attacken`, `sek. Organmanifestation`) %>% summarise(count = n()) %>% na.omit() %>% ggplot(aes(x = factor(`Anzahl Raynaud Attacken`, levels = c("NA","0", "<5", "<10", ">10", ">15", ">20")), y = count )) + geom_col() + theme_bw() + facet_grid(~`sek. Organmanifestation`) + xlab("Anzahl Raynaud Attacken") + ylab("Anzahl sek. Organmanifestation") + scale_fill_manual()
```

```{r}
#lok Herz plot
Daten %>% group_by(`Anzahl Raynaud Attacken`,Lok_Herz) %>% summarise(count = n()) %>% na.omit() %>% ggplot(aes(x = factor(`Anzahl Raynaud Attacken`, levels = c("NA","0", "<5", "<10", ">10", ">15", ">20")), y = count)) + xlab(" Anzahl Raynaud Attacken")+ ylab("Anzahl Lokalisation Herz") + geom_col() + theme_bw() + facet_grid(~Lok_Herz) 
```

```{r}
#Lok Lunge plot

Daten <- Daten %>% mutate(Lok_Lunge = ifelse(Lok_Lunge < 0, NA, Lok_Lunge))

Daten %>% group_by(`Anzahl Raynaud Attacken`, Lok_Lunge) %>% summarise(count = n()) %>% na.omit(Lok_Lunge) %>%  ggplot(aes(x = factor(`Anzahl Raynaud Attacken`, levels = c("NA","0", "<5", "<10", ">10", ">15", ">20")), y = count)) + xlab(" Anzahl Raynaud Attacken")+ ylab("Anzahl Lokalisation Lunge") + geom_col() + theme_bw() + facet_grid(~ Lok_Lunge)

```

```{r}
#Lok_Ösophagus plot
Daten %>% group_by(`Anzahl Raynaud Attacken`, Lok_Ösophagus) %>% summarise(count = n())%>% na.omit() %>% ggplot(aes(x = factor(`Anzahl Raynaud Attacken`, levels = c("NA","0", "<5", "<10", ">10", ">15", ">20")), y = count))+ xlab(" Anzahl Raynaud Attacken")+ ylab(" Anzahl Lokalisation Ösophagus") + geom_col() + theme_bw() + facet_grid(~ Lok_Ösophagus)

```

```{r}
#Lok Niere Plot

Daten %>% group_by(`Anzahl Raynaud Attacken`, Lok_Niere) %>% summarise(count = n())%>% na.omit() %>% ggplot(aes(x = factor(`Anzahl Raynaud Attacken`, levels = c("NA","0", "<5", "<10", ">10", ">15", ">20")), y = count)) + xlab(" Anzahl Raynaud Attacken")+ ylab(" Anzahl Lokalisation Niere") + geom_col() + theme_bw() + facet_grid(~Lok_Niere)
```


```{r}
# Lok Leber Plot
Daten %>% group_by(`Anzahl Raynaud Attacken`, Lok_Leber) %>% summarise(count = n())%>% na.omit() %>% ggplot(aes(x = factor(`Anzahl Raynaud Attacken`, levels = c("NA","0", "<5", "<10", ">10", ">15", ">20")), y = count)) + xlab(" Anzahl Raynaud Attacken")+ ylab("Anzahl Lokalisation Leber") + geom_col() + theme_bw() + facet_grid(~Lok_Leber)
```

